
services:
  # Frontend container
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
          - NEXT_PUBLIC_API_URL=http://localhost:3000/api/
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 30s #Acee: change to 10s in the future
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend API container
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=my_super_secret_jwt_key
      - FE_URL=http://localhost:8080,http://frontend:3000
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
      interval: 30s        
      timeout: 5s        
      retries: 5        
      start_period: 30s



  # Mongo db cloud is currently used

#   # MongoDB container
#   mongo:
#     image: mongo:4.4
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     restart: unless-stopped

# # Define volumes for persistent data
# volumes:
#   mongo-data:

networks:
  brainbytes-network:
    driver: bridge
