apiVersion: 1

datasources:
  - name: GrafanaCloud-Prometheus
    type: prometheus
    access: proxy
    url: ${GRAFANA_CLOUD_URL}
    basicAuth: true
    basicAuthUser: ${GRAFANA_CLOUD_USER}
    secureJsonData:
      basicAuthPassword: ${GRAFANA_CLOUD_PASSWORD}
    isDefault: true
    editable: true