apiVersion: 1
groups:
    - orgId: 1
      name: informational-trends
      folder: BrainBytes Folder
      interval: 30s
      rules:
        - uid: c1dfdb24-7083-484a-9952-f31e3a93f0a1
          title: LowQuestionVolume
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 43200
                to: 0
              datasourceUid: PE8EB7BB14D529B55
              model:
                editorMode: code
                expr: sum(increase(brainbytes_questions_total[12h]))
                hide: false
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1h
          annotations:
            description: Possible service degradation or user issue.
            summary: Question count dropped below 1 in 12 hours
          labels:
            severity: info
            team: product
          isPaused: false

        - uid: be8ece97-12a9-42f0-ab17-37f87e390b4f
          title: HighLearningMaterialSize
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PE8EB7BB14D529B55
              model:
                editorMode: code
                expr: sum(rate(brainbytes_learning_materials_total{byte_range=~"10000-19999|20000+"}[5m])) by (subject)
                hide: false
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 2m 
          annotations:
            description: '{{ if $value }}{{ $value }}{{ else }}0{{ end }} materials/sec being generated. Monitor storage impact'
            summary: Large learning materials created for {{ if $labels.subject }}{{ $labels.subject }}{{ else }}unknown subject{{ end }}
          labels:
            severity: info
            team: product
          isPaused: false