apiVersion: 1
groups:
  - orgId: 1
    name: BrainBytes Alerts
    folder: BrainBytes Alerts Folder
    interval: 1m
    rules:
      - uid: brainbytes_high_error_rate
        title: BrainBytes High Error Rate
        for: 5m
        condition: C
        data:
          # Block A: The Prometheus Query
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: "PBFA97CFB590B2093"
            model:
              expr: "(100 * sum(rate(brainbytes_http_requests_total{status=~\"[45]..\"}[5m])) / sum(rate(brainbytes_http_requests_total[5m]))) or vector(0)"
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A

          # Block B: Reduce
          - refId: B
            datasourceUid: "__expr__"
            model:
              type: reduce
              expression: A
              reducer: last

          # Block C: Threshold
          - refId: C
            datasourceUid: "__expr__"
            model:
              type: threshold
              expression: B
              conditions:
                - evaluator:
                    params: [5]
                    type: gt
                  operator:
                    type: and

        annotations:
          summary: "High error rate detected on BrainBytes services."
        labels:
          severity: critical