apiVersion: 1
contactPoints:
  - orgId: 1
    name: grafana-default-email
    receivers:
      - uid: default-email-receiver
        type: email
        settings:
          addresses: "${GF_SMTP_USER}"