name: BrainBytes Deploy

on:
  workflow_run:
    workflows: ["BrainBytes CI/CD"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Stack to an Environment
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Trigger Backend Render Deployment
        run: |
          echo "Triggering backend service build..."
          curl -X POST "${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}"
      
      - name: Trigger Frontend Render Deployment
        run: |
          echo "Triggering frontend service build..."
          curl -X POST "${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}"
      
      - name: Verify Live Backend Deployment
        run: |
          echo "Waiting for Backend to spin up on Render..."

          # Retry every 30 sec for 12 times = 6min total
          for i in {1..12}; do 
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://brainbytes-zovh.onrender.com/health || echo "000")
            
            if [ "$STATUS" = "200" ]; then
              echo "Success! The backend is live and healthy."
              exit 0
            fi
            
            echo "Backend Attempt $i: Status is $STATUS. Waiting 30 seconds..."
            sleep 30
          done
          
          echo "Error: Backend failed to start within 6 minutes."
          exit 1

      - name: Verify Live Frontend Deployment
        run: |
          echo "Waiting for Frontend to spin up on Render..."
          for i in {1..12}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://devops-fe-4m5i.onrender.com/ || echo "000")
            
            if [ "$STATUS" = "200" ]; then
              echo "Success! The frontend is live and healthy."
              exit 0
            fi
            
            echo "Frontend Attempt $i: Status is $STATUS. Waiting 30 seconds..."
            sleep 30
          done
          
          echo "Error: Frontend failed to start within 6 minutes."
          exit 1
